# Generated by Django 2.2.4 on 2019-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('St_date', models.CharField(max_length=500)),
                ('End_date', models.CharField(max_length=500)),
                ('Task_Id', models.CharField(max_length=500)),
                ('Task_desp', models.CharField(max_length=500)),
                ('Wla_task_des', models.CharField(max_length=500)),
                ('Resources', models.CharField(max_length=500)),
                ('Quantity', models.CharField(max_length=500)),
                ('Responsible_manager', models.CharField(max_length=500)),
                ('Location', models.CharField(max_length=500)),
                ('Chainage_from', models.CharField(max_length=500)),
                ('Chainage_To', models.CharField(max_length=500)),
            ],
        ),
    ]
